### ISSUE TITLE
Resource pack not working

### ISSUE THREAD

**Issue by cmdrlanc73** [CraftoryStudios/Craftory-External#1]
I selected yes for the custom pack when entering the server, but the blocks are not showing.

**Comment by brettsaunders21** [comment]
Would you be able to provide some more details.

Are there any errors in server console?

Have you tried stopping the server with stop command and restarting it?

What version server and client are you running?
Paper, spigot?

Thanks

**Comment by brettsaunders21** [comment]
Closed due to lack of information, no response and no issue found by community
