### ISSUE TITLE
Damage

### ISSUE THREAD

**Issue by 3Lord3** [CraftoryStudios/Craftory-External#11]
**Describe the bug**
Damage to the player closes his Menu, Chat and Inventory. If a player caught fire, he can't even write about it in the chat. The chat will close until it goes out

**To Reproduce**
1. Burn the block underneath you
2. Try to open a chat
3. See bug

**Expected behavior**
No Bug

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
I'm not sure that this particular plugin creates this problem, but when I remove it, it disappears. It's possible that Craftory conflicts with some of the plugins.

**Comment by MMJ744** [comment]
Thanks for reporting this issue, it has been fixed and will be in the next release.
