### ISSUE TITLE
Mushroom

### ISSUE THREAD

**Issue by 3Lord3** [CraftoryStudios/Craftory-External#12]
**Describe the bug**
I use the TerraformGenerator world, and it spun giant mushrooms. But because of the Craftory resource pack, I don't see any brown mushroom blocks.
(The plugin uses a complete mushroom block)

**To Reproduce**
1. Download Craftory resourcepack
2. Install TerraformGenerator or place complete mushroom block
3. See error

**Expected behavior**
The block can be seen

**Screenshots**
![image](https://user-images.githubusercontent.com/62335161/95554855-f117cf00-0a21-11eb-838b-625fee2d3ad2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
As I understand it, this block is used by Craftory because it is not used in vanilla generation. But the fungus stem block is also used, but it is visible.

**Comment by MMJ744** [comment]
Thanks for pointing this out there was an error in the resource pack. It has been fixed for the next release.
