### ISSUE TITLE
Bug texture

### ISSUE THREAD

**Issue by TheKlimoT** [CraftoryStudios/Craftory-External#14]
1. Go to place block.
2. Face of the block, looks only in one direction
![изображение](https://user-images.githubusercontent.com/26817853/96716325-91b8a800-13ad-11eb-89ef-2ca095d296f2.png)

**Comment by TheKlimoT** [comment]
![изображение](https://user-images.githubusercontent.com/26817853/96716366-9b421000-13ad-11eb-9729-4cb1addb4550.png)

**Comment by brettsaunders21** [comment]
This is not a bug, as this isn't a mod we can't get directional blocks.
