### ISSUE TITLE
Update to 1.16.5

### ISSUE THREAD

**Issue by TheRealM18** [CraftoryStudios/Craftory-External#23]
**Is your feature request related to a problem? Please describe.**
We would like to run it on our 1.16.5, but the new lock prevents us to use it.

**Describe the solution you'd like**
Change the 1.16.4 to 1.16.5

**Describe alternatives you've considered**
none

**Additional context**
errors in console

**Comment by brettsaunders21** [comment]
Updated to 1.16.5 update can be found on our website Craftory.studio
