### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by BabekDev** [CraftoryStudios/Craftory-External#7]
**Describe the bug**
![12](https://user-images.githubusercontent.com/57351015/93146253-f6ba1780-f6f6-11ea-9cc9-5502679f108f.PNG)
![13](https://user-images.githubusercontent.com/57351015/93146256-f883db00-f6f6-11ea-9049-27bf4b8b0630.PNG)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BabekDev** [comment]
Version 1.15.2

**Comment by brettsaunders21** [comment]
What version of the plugin are you using? /cr will tell you this if you don't know

**Comment by brettsaunders21** [comment]
@RuVimer Please update to the latest version. 
Minecraft 1.15.2 isn't support in version 0.2.3.
