### ISSUE TITLE
Water Wheel duplicated multiple times, and cannot remove

### ISSUE THREAD

**Issue by shadvalentine** [CraftoryStudios/Craftory-External#8]
**Describe the bug**
When I added the water wheel a few versions back, I noticed that it stopped moving, so I took the wheel out and put it back in, after doing this, the wheel duplicated visually.  I cannot figure out how to get it to go away, the machine and wheel have been removed, however the visual of multiple wheels are still showing.  This also shows for players new to the server, so it does not seem to be client side.
Running Spigot 1.16.2

**To Reproduce**
After logging back into the server, I removed the water wheel and placed it back.

**Expected behavior**
When the machine and wheel are removed the visual of the wheels should be gone too.

**Screenshots**
https://gyazo.com/cc6344e39af8b536bdcf7997699f6127

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I tried removing the entry from the .nbt file, it did not remove the wheels.

**Comment by brettsaunders21** [comment]
The actually windmill is an armour stand. As a temporary fix you can use Minecraft commands to remove it:

/minecraft:kill @e[type=ArmorStand,c=1]

Where c is a radius to kill armour stand in. Stand next to it and use a small radius like 3.

I believe this issue is fixed in the next release, @MMJ744 please can you confirm.

**Comment by MMJ744** [comment]
I believe this issue is fixed but will leave it open as it contains the solution.

If the issue persists please let us know.

**Comment by brettsaunders21** [comment]
We have had no more occurrences of this issue, so closing it
